### ISSUE TITLE
Any plans to publish via npm?

### ISSUE THREAD

**Issue by GenieTim** [antimatter15/rgb-lab#2]
Hi dear maintainer

I really appreciate the code in this repo and am considering using it for a project. Do you have any plans on publishing this as a JavaScript library to be installed using npm/yarn or is copy-pasting (or using a git submodule) the way to go? The npm module would make things easier for users in terms of automation of licence checks and updates.

Best regards,

**Comment by florabtw** [comment]
It seems like it was published by someone else, but it *is* already on npm:

```
yarn add rgb-lab
```

or

```
npm install rgb-lab
```

[npm page](https://www.npmjs.com/package/rgb-lab)
